github.com:
    users:
        Gorlof21:
            oauth_token: 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
    git_protocol: https
    user: Gorlof21
    oauth_token: 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
